name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build
    - name: Firebase Deploy
      run: |
        sudo npm install -g firebase-tools
        firebase deploy --only ${{ secrets.firebase_deploy }} --token ${{ secrets.firebase_token }}
